%% =========================================================================
%% mcs_convergence_multisite.m
%% Multi-site weather Monte Carlo pilot — IEEE 118-bus factorial scenarios
%%
%% Purpose:
%%   1) Run one master Monte Carlo sample (common random numbers).
%%   2) Evaluate nested sample sizes without re-running smaller experiments.
%%   3) Export compact CSV files for convergence, uncertainty and ranking.
%%
%% Required:
%%   MATPOWER 7.1+, Statistics and Machine Learning Toolbox
%%
%% Main outputs (results_paper/intact/):
%%   convergence_system_metrics.csv
%%   convergence_branch_lcp.csv
%%   convergence_top_branches.csv
%%   convergence_rank_stability.csv
%%   convergence_factorial_interaction.csv
%%   opf_convergence_summary.csv
%%   daily_metrics_<scenario>.csv
%%
%% Authors: Azevedo & Cunha, ISEP/IPP
%% =========================================================================

clear; clc; close all;
rng(42, 'twister');

%% AUDIT PATCH: branch loading uses max apparent power at both ends
%% Sf = hypot(PF,QF); St = hypot(PT,QT); S = max(Sf,St).
%% Output folder is separate from the earlier from-end-only run.

%% -------------------------------------------------------------------------
%% 0. Configuration
%% -------------------------------------------------------------------------
T = 24;
Ns_max = 2000;  % final publication rerun
Ns_grid = [50 100 200 400 800 1200 1600 2000];
Ns_grid = Ns_grid(Ns_grid <= Ns_max);

% Bootstrap settings. Complete 24-h trajectories are resampled as clusters.
B = 1000;      % final trajectory-bootstrap replicates
ci_level = 0.95;
bootstrap_seed = 4201;

% Operational thresholds
Tau = [0.70 0.80 0.90];
Vscreen_min = 0.95;
Vscreen_max = 1.05;
curt_tol_MW = 1e-4;

% Output controls
save_compact_mat = true;
export_daily_metrics = true;
use_parallel = true;   % Set true only after confirming MATPOWER works in parfor

% Load scaling
peak_frac = 0.70;
d_t = [0.67,0.63,0.60,0.59,0.59,0.60,0.64,0.71,0.78,0.84, ...
       0.88,0.90,0.89,0.88,0.87,0.87,0.88,0.91,0.94,0.97, ...
       1.00,0.96,0.87,0.75];

% Multi-site meteorological calibration files generated by
% calibrate_multisite_weather_v4.py. The MAT file is the principal input;
% solar_temporal_corr.csv supplies the lag-1 solar persistence coefficients.
weather_dir = 'multisite_weather';
weather_mat = fullfile(weather_dir,'multisite_weather_model.mat');
solar_temporal_csv = fullfile(weather_dir,'solar_temporal_corr.csv');
if ~exist(weather_mat,'file')
    error('Missing %s. Copy the Python-generated MAT file into the multisite_weather folder.',weather_mat);
end
if ~exist(solar_temporal_csv,'file')
    error('Missing %s. This file is needed for solar lag-1 temporal persistence.',solar_temporal_csv);
end
W = load(weather_mat);
required_fields = {'solar_alpha_hourly','solar_beta_hourly','solar_envelope_norm', ...
    'solar_corr_gaussian','wind_k_weibull','wind_c_weibull_ms', ...
    'wind_rho_ar1','wind_corr_gaussian'};
for ii=1:numel(required_fields)
    if ~isfield(W,required_fields{ii})
        error('Field %s is absent from %s.',required_fields{ii},weather_mat);
    end
end
nzone = size(W.solar_corr_gaussian,1);
if nzone ~= 6
    error('Expected six generic meteorological zones, found %d.',nzone);
end
Tsol = readtable(solar_temporal_csv,'TextType','string');
solar_rho_ar1 = NaN(nzone,1);
for iz=1:nzone
    zid = sprintf('Z%d_',iz);
    mask = startsWith(Tsol.zone,zid) & Tsol.lag_hours==1;
    if nnz(mask)~=1
        error('Could not identify one lag-1 solar correlation for zone %d.',iz);
    end
    solar_rho_ar1(iz)=Tsol.correlation(mask);
end
v_ci = 3.0; v_r = 12.0; v_co = 25.0;
% Factorial scenarios
P_solar_low  = 200; P_wind_low  = 300;
P_solar_high = 400; P_wind_high = 600;

CONC.solar_buses = 45;      CONC.wind_buses = 75;
CONC.solar_frac  = 1.0;     CONC.wind_frac  = 1.0;
DIST.solar_buses = [9 45];  DIST.wind_buses = [50 75];
DIST.solar_frac  = [0.4 0.6];
DIST.wind_frac   = [0.35 0.65];

% Generic meteorological-zone assignments. These do not geographically
% embed the IEEE 118-bus network; they only represent diversified weather.
CONC.solar_zones = 4;       % Z4_CI
CONC.wind_zones  = 3;       % Z3_CW
DIST.solar_zones = [2 5];   % Z2_NE, Z5_SW
DIST.wind_zones  = [1 6];   % Z1_NW, Z6_SE

sc118(1) = make_scenario('S1_Low_Conc',  'Low/Concentrated',  P_solar_low,  P_wind_low,  CONC);
sc118(2) = make_scenario('S2_High_Conc', 'High/Concentrated', P_solar_high, P_wind_high, CONC);
sc118(3) = make_scenario('S3_Low_Dist',  'Low/Distributed',   P_solar_low,  P_wind_low,  DIST);
sc118(4) = make_scenario('S4_High_Dist', 'High/Distributed',  P_solar_high, P_wind_high, DIST);

outdir = fullfile('results_paper', 'intact');
if ~exist(outdir, 'dir'), mkdir(outdir); end

mpopt = mpoption('verbose', 0, 'out.all', 0);

% Reproducibility metadata
try
    matlab_release = version('-release');
catch
    matlab_release = version;
end
try
    [mpv, ~] = mpver;
    matpower_version = string(mpv);
catch
    try
        matpower_version = string(strtrim(evalc('mpver')));
    catch
        matpower_version = "unknown";
    end
end
try
    resolved_ac_solver = string(mpopt.opf.ac.solver);
    if strlength(resolved_ac_solver)==0
        resolved_ac_solver = "MATPOWER default/automatic";
    end
catch
    resolved_ac_solver = "MATPOWER default/automatic";
end
try
    pool_now = gcp('nocreate');
    if isempty(pool_now), parallel_workers_at_setup = 0; else, parallel_workers_at_setup = pool_now.NumWorkers; end
catch
    parallel_workers_at_setup = NaN;
end
Tsoftware = table(string(matlab_release),string(matpower_version),string(resolved_ac_solver), ...
    parallel_workers_at_setup,string(computer('arch')), ...
    'VariableNames',{'MATLABRelease','MATPOWERVersion','ResolvedACOPFSolver', ...
    'ParallelWorkersAtSetup','ComputerArchitecture'});
writetable(Tsoftware,fullfile(outdir,'software_environment.csv'));


fprintf('=== Multi-site weather Monte Carlo pilot ===\n');
fprintf('Master sample: Ns_max = %d trajectories (%d hours each)\n', Ns_max, T);
fprintf('Nested sample sizes: %s\n', mat2str(Ns_grid));
fprintf('Bootstrap replicates: B = %d\n', B);

%% -------------------------------------------------------------------------
%% 1. Master multi-site renewable trajectory pool
%% -------------------------------------------------------------------------
fprintf('\n[1] Generating spatially and temporally correlated renewable trajectories...\n');

% Gaussian latent processes have target same-hour spatial covariance R and
% site-specific AR(1) persistence. The innovation covariance is
% Q = R - A*R*A'. Small numerical non-PSD components are projected away.
Xsolar = generate_vector_ar1(Ns_max,T,W.solar_corr_gaussian,solar_rho_ar1);
Xwind  = generate_vector_ar1(Ns_max,T,W.wind_corr_gaussian,W.wind_rho_ar1(:));

Usolar = min(max(normcdf(Xsolar),1e-8),1-1e-8);
Uwind  = min(max(normcdf(Xwind), 1e-8),1-1e-8);

G_solar_zone = zeros(Ns_max,T,nzone);
P_wind_zone  = zeros(Ns_max,T,nzone);
for iz=1:nzone
    for t=1:T
        a = W.solar_alpha_hourly(iz,t);
        b = W.solar_beta_hourly(iz,t);
        env = W.solar_envelope_norm(iz,t);
        if env<=0 || ~isfinite(a) || ~isfinite(b) || a<=0 || b<=0
            G_solar_zone(:,t,iz)=0;
        else
            G_solar_zone(:,t,iz)=betainv(Usolar(:,t,iz),a,b)*env;
        end
    end
    v = wblinv(Uwind(:,:,iz),W.wind_c_weibull_ms(iz),W.wind_k_weibull(iz));
    P_wind_zone(:,:,iz)=wind_pc(v,v_ci,v_r,v_co,1.0);
end

fprintf('[1] Generated arrays: solar %s, wind %s.\n', ...
    mat2str(size(G_solar_zone)),mat2str(size(P_wind_zone)));

%% -------------------------------------------------------------------------
%% 2. Network and deterministic no-RES baseline
%% -------------------------------------------------------------------------
fprintf('\n[2] Loading PGLib IEEE 118-bus case and running baseline...\n');

mpc118 = loadcase('./case_pglib_opf_case118_ieee.m');
nb = size(mpc118.bus,1);
nbr = size(mpc118.branch,1);
Ppk = sum(mpc118.bus(:,3));
Pd_frac = mpc118.bus(:,3) / Ppk;
Qd0 = mpc118.bus(:,4);
Ppk_scaled = Ppk * peak_frac;
Prat = mpc118.branch(:,6);

if any(~isfinite(Prat) | Prat <= 0)
    error('All branches must have a positive finite RATE_A.');
end

base_success = false(T,1);
base_time = NaN(T,1);
base_cost = NaN(T,1);
base_loss = NaN(T,1);
base_S = NaN(T,nbr);
base_V = NaN(T,nb);

% Unrecorded warm-up solve to reduce first-call timing bias
mt_warm = mpc118;
Plt = Ppk_scaled*d_t(1);
mt_warm.bus(:,3) = Pd_frac*Plt;
mt_warm.bus(:,4) = Qd0*(Plt/Ppk);
runopf(mt_warm, mpopt);

for t = 1:T
    mt = mpc118;
    Plt = Ppk_scaled*d_t(t);
    mt.bus(:,3) = Pd_frac*Plt;
    mt.bus(:,4) = Qd0*(Plt/Ppk);
    ts = tic;
    r = runopf(mt, mpopt);
    base_time(t) = toc(ts);
    base_success(t) = logical(r.success);
    if r.success
        base_cost(t) = r.f;
        base_loss(t) = sum(r.branch(:,14) + r.branch(:,16));
        base_S(t,:) = max(hypot(r.branch(:,14), r.branch(:,15)), hypot(r.branch(:,16), r.branch(:,17)));
        base_V(t,:) = r.bus(:,8)';
    end
end

if ~all(base_success)
    warning('No-RES baseline has %d failed hours.', nnz(~base_success));
end

base_LCP = NaN(nbr, numel(Tau));
for j = 1:numel(Tau)
    base_LCP(:,j) = mean(base_S > Tau(j)*Prat', 1, 'omitnan')' * 100;
end

fprintf('[2] Baseline success rate: %.2f%%\n', 100*mean(base_success));

%% -------------------------------------------------------------------------
%% 3. Run master sample once for each factorial scenario
%% -------------------------------------------------------------------------
% Compact per-trajectory storage:
%   exceed_count(s,branch,threshold) = number of exceeding hours (0..24)
%   daily_* = one number per 24-h trajectory

nsc = numel(sc118);
res = repmat(struct(), nsc, 1);

for sc = 1:nsc
    cfg = sc118(sc);
    fprintf('\n[3] Scenario %d/%d: %s\n', sc, nsc, cfg.label);

    [mpc_sc, idx_s, idx_w] = add_res_generators(mpc118, cfg);

    [Psolar_units,Pwind_units] = scenario_available_power(cfg,G_solar_zone,P_wind_zone);

    exceed_count = zeros(Ns_max, nbr, numel(Tau), 'uint8');
    voltage_violation_count = zeros(Ns_max, nb, 'uint8');
    daily_cost = NaN(Ns_max,1);
    daily_loss_MWh = NaN(Ns_max,1);
    daily_solar_curt_MWh = NaN(Ns_max,1);
    daily_wind_curt_MWh = NaN(Ns_max,1);
    max_solar_curt_MW = NaN(Ns_max,1);
    max_wind_curt_MW = NaN(Ns_max,1);
    curtailed_hours = NaN(Ns_max,1);
    successful_hours = zeros(Ns_max,1,'uint8');
    total_solve_time_s = NaN(Ns_max,1);

    tscenario = tic;

    if use_parallel
        parfor s = 1:Ns_max
            day = run_day_multisite(mpc_sc, squeeze(Psolar_units(s,:,:)), squeeze(Pwind_units(s,:,:)), ...
                idx_s, idx_w, ...
                Pd_frac, Qd0, Ppk_scaled, Ppk, d_t, Prat, Tau, ...
                Vscreen_min, Vscreen_max, curt_tol_MW, mpopt);

            exceed_count(s,:,:) = day.exceed_count;
            voltage_violation_count(s,:) = day.voltage_violation_count;
            daily_cost(s) = day.daily_cost;
            daily_loss_MWh(s) = day.daily_loss_MWh;
            daily_solar_curt_MWh(s) = day.daily_solar_curt_MWh;
            daily_wind_curt_MWh(s) = day.daily_wind_curt_MWh;
            max_solar_curt_MW(s) = day.max_solar_curt_MW;
            max_wind_curt_MW(s) = day.max_wind_curt_MW;
            curtailed_hours(s) = day.curtailed_hours;
            successful_hours(s) = day.successful_hours;
            total_solve_time_s(s) = day.total_solve_time_s;
        end
    else
        for s = 1:Ns_max
            day = run_day_multisite(mpc_sc, squeeze(Psolar_units(s,:,:)), squeeze(Pwind_units(s,:,:)), ...
                idx_s, idx_w, ...
                Pd_frac, Qd0, Ppk_scaled, Ppk, d_t, Prat, Tau, ...
                Vscreen_min, Vscreen_max, curt_tol_MW, mpopt);

            exceed_count(s,:,:) = day.exceed_count;
            voltage_violation_count(s,:) = day.voltage_violation_count;
            daily_cost(s) = day.daily_cost;
            daily_loss_MWh(s) = day.daily_loss_MWh;
            daily_solar_curt_MWh(s) = day.daily_solar_curt_MWh;
            daily_wind_curt_MWh(s) = day.daily_wind_curt_MWh;
            max_solar_curt_MW(s) = day.max_solar_curt_MW;
            max_wind_curt_MW(s) = day.max_wind_curt_MW;
            curtailed_hours(s) = day.curtailed_hours;
            successful_hours(s) = day.successful_hours;
            total_solve_time_s(s) = day.total_solve_time_s;

            if mod(s,50)==0 || s==Ns_max
                elapsed = toc(tscenario);
                eta = elapsed/s*(Ns_max-s);
                fprintf('  trajectory %d/%d | elapsed %.1f min | ETA %.1f min\n', ...
                    s, Ns_max, elapsed/60, eta/60);
            end
        end
    end

    res(sc).name = cfg.name;
    res(sc).label = cfg.label;
    res(sc).exceed_count = exceed_count;
    res(sc).voltage_violation_count = voltage_violation_count;
    res(sc).daily_cost = daily_cost;
    res(sc).daily_loss_MWh = daily_loss_MWh;
    res(sc).daily_solar_curt_MWh = daily_solar_curt_MWh;
    res(sc).daily_wind_curt_MWh = daily_wind_curt_MWh;
    res(sc).max_solar_curt_MW = max_solar_curt_MW;
    res(sc).max_wind_curt_MW = max_wind_curt_MW;
    res(sc).curtailed_hours = curtailed_hours;
    res(sc).successful_hours = successful_hours;
    res(sc).total_solve_time_s = total_solve_time_s;

    if export_daily_metrics
        Tdaily = table((1:Ns_max)', double(successful_hours), total_solve_time_s, ...
            daily_cost, daily_loss_MWh, daily_solar_curt_MWh, daily_wind_curt_MWh, ...
            max_solar_curt_MW, max_wind_curt_MW, curtailed_hours, ...
            'VariableNames', {'trajectory','successful_hours','solve_time_s', ...
            'daily_cost','daily_loss_MWh','solar_curt_MWh','wind_curt_MWh', ...
            'max_solar_curt_MW','max_wind_curt_MW','curtailed_hours'});
        writetable(Tdaily, fullfile(outdir, sprintf('daily_metrics_%s.csv',cfg.name)));
    end
end

%% -------------------------------------------------------------------------
%% 4. OPF convergence summary
%% -------------------------------------------------------------------------
scenario = strings(nsc+1,1);
requested_OPFs = zeros(nsc+1,1);
successful_OPFs = zeros(nsc+1,1);
failed_OPFs = zeros(nsc+1,1);
success_rate_pct = zeros(nsc+1,1);
mean_solve_time_s = zeros(nsc+1,1);
median_solve_time_s = zeros(nsc+1,1);
p95_solve_time_s = zeros(nsc+1,1);

scenario(1) = "BASE_NoRES";
requested_OPFs(1) = T;
successful_OPFs(1) = nnz(base_success);
failed_OPFs(1) = T-successful_OPFs(1);
success_rate_pct(1) = 100*successful_OPFs(1)/T;
mean_solve_time_s(1) = mean(base_time,'omitnan');
median_solve_time_s(1) = median(base_time,'omitnan');
p95_solve_time_s(1) = prctile(base_time,95);

for sc = 1:nsc
    scenario(sc+1) = string(res(sc).name);
    requested_OPFs(sc+1) = Ns_max*T;
    successful_OPFs(sc+1) = sum(double(res(sc).successful_hours));
    failed_OPFs(sc+1) = requested_OPFs(sc+1)-successful_OPFs(sc+1);
    success_rate_pct(sc+1) = 100*successful_OPFs(sc+1)/requested_OPFs(sc+1);
    per_hour_time = res(sc).total_solve_time_s/T;
    mean_solve_time_s(sc+1) = mean(per_hour_time,'omitnan');
    median_solve_time_s(sc+1) = median(per_hour_time,'omitnan');
    p95_solve_time_s(sc+1) = prctile(per_hour_time,95);
end

Topf = table(scenario,requested_OPFs,successful_OPFs,failed_OPFs,success_rate_pct, ...
    mean_solve_time_s,median_solve_time_s,p95_solve_time_s);
writetable(Topf, fullfile(outdir,'opf_convergence_summary.csv'));

%% -------------------------------------------------------------------------
%% 5. Nested-sample convergence and trajectory bootstrap confidence intervals
%% -------------------------------------------------------------------------
fprintf('\n[5] Computing nested-sample convergence and bootstrap intervals...\n');
rng(bootstrap_seed,'twister');

% Identify branch of greatest positive Delta-LCP80 using full master sample.
full_LCP80 = zeros(nbr,nsc);
for sc = 1:nsc
    full_LCP80(:,sc) = squeeze(mean(double(res(sc).exceed_count(:,:,2)),1))'/T*100;
end
full_delta80 = full_LCP80 - base_LCP(:,2);
[~, interaction_branch] = max(max(full_delta80,[],2));

system_rows = {};
branch_rows = {};
top_rows = {};
rank_rows = {};
interaction_rows = {};
paired_rows = {};

% Rank-stability settings. Branches below this Delta-LCP magnitude in both
% the current and reference sample are excluded from Spearman calculation.
rank_min_abs_delta_pp = 0.5;

for iN = 1:numel(Ns_grid)
    N = Ns_grid(iN);
    idxN = 1:N;
    fprintf('  N = %d\n', N);

    % Full-N branch rankings for rank-stability comparison
    LCP80_N = zeros(nbr,nsc);

    for sc = 1:nsc
        R = res(sc);
        valid_day = double(R.successful_hours(idxN)) == T;
        valid_idx = idxN(valid_day);
        n_valid = numel(valid_idx);

        if n_valid == 0
            error('No complete valid trajectories for %s at N=%d.',R.name,N);
        end

        % System-level metrics with cluster-bootstrap CIs
        system_defs = {
            'daily_cost',              R.daily_cost(valid_idx),              'currency/day';
            'daily_loss_MWh',          R.daily_loss_MWh(valid_idx),          'MWh/day';
            'solar_curt_MWh',          R.daily_solar_curt_MWh(valid_idx),    'MWh/day';
            'wind_curt_MWh',           R.daily_wind_curt_MWh(valid_idx),     'MWh/day';
            'curtailed_hours',          R.curtailed_hours(valid_idx),         'h/day';
            'trajectory_curt_prob_pct', double(R.curtailed_hours(valid_idx)>0)*100, '%'
            };

        for im = 1:size(system_defs,1)
            metric_name = system_defs{im,1};
            values = system_defs{im,2};
            unit = system_defs{im,3};
            [estimate, se, ci_low, ci_high] = bootstrap_mean(values, B, ci_level);
            system_rows(end+1,:) = {N,n_valid,string(R.name),string(R.label), ...
                string(metric_name),estimate,se,ci_low,ci_high,string(unit)}; %#ok<SAGROW>
        end

        % Branch-level LCP and Delta-LCP for all branches and thresholds
        for jt = 1:numel(Tau)
            daily_counts = double(R.exceed_count(valid_idx,:,jt)); % n_valid x nbr
            p_hat = mean(daily_counts,1)/T*100;
            [se_vec, lo_vec, hi_vec] = bootstrap_lcp_matrix(daily_counts,T,B,ci_level);
            delta_hat = p_hat' - base_LCP(:,jt);
            delta_lo = lo_vec' - base_LCP(:,jt);
            delta_hi = hi_vec' - base_LCP(:,jt);

            if jt == 2
                LCP80_N(:,sc) = p_hat';
            end

            for br = 1:nbr
                branch_rows(end+1,:) = {N,n_valid,string(R.name),Tau(jt),br, ...
                    mpc118.branch(br,1),mpc118.branch(br,2),Prat(br), ...
                    base_LCP(br,jt),p_hat(br),se_vec(br),lo_vec(br),hi_vec(br), ...
                    delta_hat(br),delta_lo(br),delta_hi(br)}; %#ok<SAGROW>
            end
        end

        % Top 10 LCP80 and top 10 positive Delta-LCP80 at this N
        d80 = LCP80_N(:,sc)-base_LCP(:,2);
        [~,ord_lcp] = sort(LCP80_N(:,sc),'descend');
        [~,ord_delta] = sort(d80,'descend');
        ord_lcp = ord_lcp(1:10);
        ord_delta = ord_delta(1:10);

        for rank = 1:10
            br = ord_lcp(rank);
            top_rows(end+1,:) = {N,string(R.name),"LCP80",rank,br, ...
                mpc118.branch(br,1),mpc118.branch(br,2),LCP80_N(br,sc)}; %#ok<SAGROW>
            br = ord_delta(rank);
            top_rows(end+1,:) = {N,string(R.name),"DeltaLCP80",rank,br, ...
                mpc118.branch(br,1),mpc118.branch(br,2),d80(br)}; %#ok<SAGROW>
        end

        % Ranking stability relative to Ns_max ranking.
        % Exclude branches that are effectively uninformative in both samples,
        % and use tie-aware top-k sets with Jaccard overlap.
        ref_d80 = full_delta80(:,sc);
        informative = (abs(ref_d80) >= rank_min_abs_delta_pp) | ...
                      (abs(d80) >= rank_min_abs_delta_pp);

        if nnz(informative) >= 3 && ...
                numel(unique(ref_d80(informative))) >= 2 && ...
                numel(unique(d80(informative))) >= 2
            rho_s = corr(d80(informative),ref_d80(informative), ...
                'Type','Spearman','Rows','complete');
        else
            rho_s = NaN;
        end

        top5_current = topk_with_ties(d80,5,rank_min_abs_delta_pp);
        top5_ref     = topk_with_ties(ref_d80,5,rank_min_abs_delta_pp);
        top10_current = topk_with_ties(d80,10,rank_min_abs_delta_pp);
        top10_ref     = topk_with_ties(ref_d80,10,rank_min_abs_delta_pp);

        top5_overlap = jaccard_pct(top5_current,top5_ref);
        top10_overlap = jaccard_pct(top10_current,top10_ref);

        rank_rows(end+1,:) = {N,string(R.name),nnz(informative), ...
            rho_s,top5_overlap,top10_overlap, ...
            numel(top5_current),numel(top5_ref), ...
            numel(top10_current),numel(top10_ref)}; %#ok<SAGROW>
    end

    % Paired scenario contrasts using common random numbers.
    % Positive estimate means the first scenario has a larger metric.
    pair_defs = {
        1,3,'S1_minus_S3','Low penetration: concentrated minus distributed';
        2,4,'S2_minus_S4','High penetration: concentrated minus distributed';
        2,1,'S2_minus_S1','Concentrated: high minus low penetration';
        4,3,'S4_minus_S3','Distributed: high minus low penetration'
        };

    metric_defs = {
        'daily_cost','currency/day';
        'daily_loss_MWh','MWh/day';
        'daily_solar_curt_MWh','MWh/day';
        'daily_wind_curt_MWh','MWh/day';
        'curtailed_hours','h/day'
        };

    for ip = 1:size(pair_defs,1)
        ia = pair_defs{ip,1}; ib = pair_defs{ip,2};
        pair_id = string(pair_defs{ip,3});
        pair_label = string(pair_defs{ip,4});
        joint_valid = double(res(ia).successful_hours(idxN))==T & ...
                      double(res(ib).successful_hours(idxN))==T;
        joint_idx = idxN(joint_valid);

        for im = 1:size(metric_defs,1)
            field_name = metric_defs{im,1};
            unit = string(metric_defs{im,2});
            xa = double(res(ia).(field_name)(joint_idx));
            xb = double(res(ib).(field_name)(joint_idx));
            [estimate,se,ci_low,ci_high] = bootstrap_paired_difference(xa,xb,B,ci_level);
            paired_rows(end+1,:) = {N,numel(joint_idx),pair_id,pair_label, ...
                string(field_name),estimate,se,ci_low,ci_high,unit}; %#ok<SAGROW>
        end

        % Paired contrast in trajectory-level LCP80 at the selected interaction branch.
        xa = double(res(ia).exceed_count(joint_idx,interaction_branch,2))/T*100;
        xb = double(res(ib).exceed_count(joint_idx,interaction_branch,2))/T*100;
        [estimate,se,ci_low,ci_high] = bootstrap_paired_difference(xa,xb,B,ci_level);
        paired_rows(end+1,:) = {N,numel(joint_idx),pair_id,pair_label, ...
            "LCP80_interaction_branch_pp",estimate,se,ci_low,ci_high,"percentage points"}; %#ok<SAGROW>
    end

    % Factorial interaction at the branch selected from the full sample.
    % Scenario order: S1 LC, S2 HC, S3 LD, S4 HD.
    daily_pp = cell(4,1);
    for sc = 1:4
        valid = double(res(sc).successful_hours(idxN))==T;
        valid_idx = idxN(valid);
        daily_pp{sc} = double(res(sc).exceed_count(valid_idx,interaction_branch,2))/T*100 ...
            - base_LCP(interaction_branch,2);
    end
    [Ihat,Ise,Ilo,Ihi] = bootstrap_interaction(daily_pp,B,ci_level);
    interaction_rows(end+1,:) = {N,interaction_branch, ...
        mpc118.branch(interaction_branch,1),mpc118.branch(interaction_branch,2), ...
        Ihat,Ise,Ilo,Ihi}; %#ok<SAGROW>
end

%% -------------------------------------------------------------------------
%% 6. Write compact CSV outputs
%% -------------------------------------------------------------------------
Tsystem = cell2table(system_rows,'VariableNames', ...
    {'N_requested','N_valid','scenario','scenario_label','metric','estimate','bootstrap_se', ...
     'ci_low','ci_high','unit'});
writetable(Tsystem,fullfile(outdir,'convergence_system_metrics.csv'));

Tbranch = cell2table(branch_rows,'VariableNames', ...
    {'N_requested','N_valid','scenario','threshold','branch_idx','from_bus','to_bus','rating_MVA', ...
     'base_LCP_pct','LCP_pct','bootstrap_se_pp','LCP_ci_low_pct','LCP_ci_high_pct', ...
     'DeltaLCP_pp','DeltaLCP_ci_low_pp','DeltaLCP_ci_high_pp'});
writetable(Tbranch,fullfile(outdir,'convergence_branch_lcp.csv'));

Ttop = cell2table(top_rows,'VariableNames', ...
    {'N_requested','scenario','ranking_metric','rank','branch_idx','from_bus','to_bus','value'});
writetable(Ttop,fullfile(outdir,'convergence_top_branches.csv'));

Trank = cell2table(rank_rows,'VariableNames', ...
    {'N_requested','scenario','n_informative_branches','spearman_vs_Nmax', ...
     'top5_jaccard_pct','top10_jaccard_pct','top5_current_set_size','top5_ref_set_size', ...
     'top10_current_set_size','top10_ref_set_size'});
writetable(Trank,fullfile(outdir,'convergence_rank_stability.csv'));

Tinteraction = cell2table(interaction_rows,'VariableNames', ...
    {'N_requested','branch_idx','from_bus','to_bus','interaction_pp','bootstrap_se_pp', ...
     'ci_low_pp','ci_high_pp'});
writetable(Tinteraction,fullfile(outdir,'convergence_factorial_interaction.csv'));

Tpaired = cell2table(paired_rows,'VariableNames', ...
    {'N_requested','N_valid_pairs','contrast','contrast_label','metric','estimate_A_minus_B', ...
     'bootstrap_se','ci_low','ci_high','unit'});
writetable(Tpaired,fullfile(outdir,'convergence_paired_scenario_differences.csv'));

% Small file for representative branches: full-sample top Delta-LCP80 branches
representative = unique([interaction_branch; find_branch(mpc118,94,100); find_branch(mpc118,26,30)]);
Trep = Tbranch(ismember(Tbranch.branch_idx,representative) & Tbranch.threshold==0.80,:);
writetable(Trep,fullfile(outdir,'convergence_representative_branches.csv'));

if save_compact_mat
    save(fullfile(outdir,'convergence_compact.mat'), ...
        'res','base_LCP','base_cost','base_loss','base_success','base_time', ...
        'mpc118','Prat','Tau','Ns_grid','Ns_max','T','sc118','interaction_branch', ...
        'G_solar_zone','P_wind_zone','solar_rho_ar1','W','peak_frac','d_t','-v7.3');
end

fprintf('\n=== Convergence experiment completed ===\n');
fprintf('Outputs written to: %s\n',outdir);
fprintf('Primary files to share for analysis:\n');
fprintf('  convergence_system_metrics.csv\n');
fprintf('  convergence_representative_branches.csv\n');
fprintf('  convergence_rank_stability.csv\n');
fprintf('  convergence_paired_scenario_differences.csv\n');
fprintf('  convergence_factorial_interaction.csv\n');
fprintf('  opf_convergence_summary.csv\n');

%% =========================================================================
%% Local functions
%% =========================================================================
function sc = make_scenario(name,label,Ps,Pw,inj)
    sc.name = name;
    sc.label = label;
    sc.P_solar_max = Ps;
    sc.P_wind_max = Pw;
    sc.inj = inj;
end

function P = wind_pc(v,vci,vr,vco,Prated)
    P = zeros(size(v));
    r1 = (v>=vci) & (v<=vr);
    P(r1) = Prated*(v(r1).^3-vci^3)/(vr^3-vci^3);
    P(v>vr & v<vco) = Prated;
end

function [mpc,idx_s,idx_w] = add_res_generators(mpc0,cfg)
    mpc = mpc0;
    idx_s = zeros(1,numel(cfg.inj.solar_buses));
    idx_w = zeros(1,numel(cfg.inj.wind_buses));

    for i = 1:numel(cfg.inj.solar_buses)
        Pi = cfg.P_solar_max*cfg.inj.solar_frac(i);
        row = zeros(1,size(mpc.gen,2));
        row(1:10) = [cfg.inj.solar_buses(i),0,0,0.5*Pi,-0.5*Pi,1,100,1,Pi,0];
        mpc.gen = [mpc.gen;row];
        mpc.gencost = [mpc.gencost;zero_cost_row(mpc.gencost)];
        idx_s(i) = size(mpc.gen,1);
    end

    for i = 1:numel(cfg.inj.wind_buses)
        Pi = cfg.P_wind_max*cfg.inj.wind_frac(i);
        row = zeros(1,size(mpc.gen,2));
        row(1:10) = [cfg.inj.wind_buses(i),0,0,0.5*Pi,-0.5*Pi,1,100,1,Pi,0];
        mpc.gen = [mpc.gen;row];
        mpc.gencost = [mpc.gencost;zero_cost_row(mpc.gencost)];
        idx_w(i) = size(mpc.gen,1);
    end
end

function gc = zero_cost_row(gencost)
    ncol = size(gencost,2);
    gc = zeros(1,ncol);
    gc(1)=2;
    gc(4)=ncol-4;
end

function [Psolar_units,Pwind_units] = scenario_available_power(cfg,Gzone,Wzone)
    Ns=size(Gzone,1); T=size(Gzone,2);
    ns=numel(cfg.inj.solar_buses); nw=numel(cfg.inj.wind_buses);
    Psolar_units=zeros(Ns,T,ns); Pwind_units=zeros(Ns,T,nw);
    if numel(cfg.inj.solar_zones)~=ns || numel(cfg.inj.wind_zones)~=nw
        error('Zone mapping length does not match generator count for %s.',cfg.name);
    end
    for i=1:ns
        Psolar_units(:,:,i)=cfg.P_solar_max*cfg.inj.solar_frac(i)*Gzone(:,:,cfg.inj.solar_zones(i));
    end
    for i=1:nw
        Pwind_units(:,:,i)=cfg.P_wind_max*cfg.inj.wind_frac(i)*Wzone(:,:,cfg.inj.wind_zones(i));
    end
end

function X = generate_vector_ar1(Ns,T,R,rho)
    R=(R+R')/2;
    rho=rho(:);
    nz=numel(rho);
    A=diag(rho);
    Q=R-A*R*A';
    R=nearest_corr(R,1e-10);
    Q=project_psd(R-A*R*A',1e-10);
    L0=chol(R,'lower');
    Lq=chol(Q,'lower');
    X=zeros(Ns,T,nz);
    X(:,1,:)=randn(Ns,nz)*L0';
    for t=2:T
        prev=squeeze(X(:,t-1,:));
        eps=randn(Ns,nz)*Lq';
        X(:,t,:)=prev*A'+eps;
    end
end

function M = project_psd(M,tol)
    M=(M+M')/2;
    [V,D]=eig(M);
    d=diag(D);
    d(d<tol)=tol;
    M=V*diag(d)*V';
    M=(M+M')/2;
end

function R = nearest_corr(R,tol)
    R=project_psd(R,tol);
    s=sqrt(diag(R));
    R=R./(s*s');
    R=project_psd((R+R')/2,tol);
    s=sqrt(diag(R));
    R=R./(s*s');
    R=(R+R')/2;
end

function day = run_day_multisite(mpc,Ps_units,Pw_units,idx_s,idx_w, ...
    Pd_frac,Qd0,Ppk_scaled,Ppk,d_t,Prat,Tau,Vmin,Vmax,curt_tol,mpopt)

    T = numel(d_t);
    if isvector(Ps_units), Ps_units=Ps_units(:); end
    if isvector(Pw_units), Pw_units=Pw_units(:); end
    if size(Ps_units,1)~=T, Ps_units=Ps_units'; end
    if size(Pw_units,1)~=T, Pw_units=Pw_units'; end
    nbr = size(mpc.branch,1); nb = size(mpc.bus,1);
    exceed=false(T,nbr,numel(Tau)); vviol=false(T,nb);
    costs=NaN(T,1); losses=NaN(T,1); curtS=NaN(T,1); curtW=NaN(T,1);
    ok=false(T,1); solve_time=NaN(T,1);

    for t=1:T
        mt=mpc; Plt=Ppk_scaled*d_t(t);
        mt.bus(:,3)=Pd_frac*Plt; mt.bus(:,4)=Qd0*(Plt/Ppk);
        for i=1:numel(idx_s), mt.gen(idx_s(i),9)=Ps_units(t,i); end
        for i=1:numel(idx_w), mt.gen(idx_w(i),9)=Pw_units(t,i); end
        ts=tic; r=runopf(mt,mpopt); solve_time(t)=toc(ts); ok(t)=logical(r.success);
        if r.success
            S=max(hypot(r.branch(:,14),r.branch(:,15)), hypot(r.branch(:,16),r.branch(:,17))); V=r.bus(:,8);
            for j=1:numel(Tau), exceed(t,:,j)=(S>Tau(j)*Prat)'; end
            vviol(t,:)=(V<Vmin | V>Vmax)'; costs(t)=r.f;
            losses(t)=sum(r.branch(:,14)+r.branch(:,16));
            curtS(t)=sum(max(0,Ps_units(t,:)'-r.gen(idx_s,2)));
            curtW(t)=sum(max(0,Pw_units(t,:)'-r.gen(idx_w,2)));
            if curtS(t)<curt_tol, curtS(t)=0; end
            if curtW(t)<curt_tol, curtW(t)=0; end
        end
    end
    if all(ok)
        day.exceed_count=uint8(squeeze(sum(exceed,1)));
        day.voltage_violation_count=uint8(sum(vviol,1));
        day.daily_cost=sum(costs); day.daily_loss_MWh=sum(losses);
        day.daily_solar_curt_MWh=sum(curtS); day.daily_wind_curt_MWh=sum(curtW);
        day.max_solar_curt_MW=max(curtS); day.max_wind_curt_MW=max(curtW);
        day.curtailed_hours=nnz((curtS+curtW)>curt_tol);
    else
        day.exceed_count=zeros(nbr,numel(Tau),'uint8');
        day.voltage_violation_count=zeros(1,nb,'uint8');
        day.daily_cost=NaN; day.daily_loss_MWh=NaN;
        day.daily_solar_curt_MWh=NaN; day.daily_wind_curt_MWh=NaN;
        day.max_solar_curt_MW=NaN; day.max_wind_curt_MW=NaN; day.curtailed_hours=NaN;
    end
    day.successful_hours=uint8(nnz(ok));
    day.total_solve_time_s=sum(solve_time,'omitnan');
end

function [estimate,se,lo,hi] = bootstrap_mean(x,B,ci_level)
    x=x(:); x=x(isfinite(x));
    n=numel(x);
    estimate=mean(x);
    if n<2
        se=NaN; lo=NaN; hi=NaN; return;
    end
    boot=zeros(B,1);
    for b=1:B
        idx=randi(n,n,1);
        boot(b)=mean(x(idx));
    end
    se=std(boot,0);
    alpha=(1-ci_level)/2;
    q=prctile(boot,[100*alpha,100*(1-alpha)]);
    lo=q(1); hi=q(2);
end

function [se,lo,hi] = bootstrap_lcp_matrix(daily_counts,T,B,ci_level)
    [n,nbr]=size(daily_counts);
    boot=zeros(B,nbr,'single');
    for b=1:B
        idx=randi(n,n,1);
        boot(b,:)=single(mean(daily_counts(idx,:),1)/T*100);
    end
    se=std(double(boot),0,1);
    alpha=(1-ci_level)/2;
    q=prctile(double(boot),[100*alpha,100*(1-alpha)],1);
    lo=q(1,:); hi=q(2,:);
end

function [estimate,se,lo,hi] = bootstrap_interaction(daily_pp,B,ci_level)
    means=cellfun(@mean,daily_pp);
    estimate=(means(2)-means(1))-(means(4)-means(3));
    boot=zeros(B,1);
    for b=1:B
        m=zeros(4,1);
        for sc=1:4
            x=daily_pp{sc}; n=numel(x);
            m(sc)=mean(x(randi(n,n,1)));
        end
        boot(b)=(m(2)-m(1))-(m(4)-m(3));
    end
    se=std(boot,0);
    alpha=(1-ci_level)/2;
    q=prctile(boot,[100*alpha,100*(1-alpha)]);
    lo=q(1); hi=q(2);
end

function idx=topk_with_ties(x,k,min_abs_value)
    x=x(:);
    eligible=find(isfinite(x) & abs(x)>=min_abs_value);
    if isempty(eligible)
        idx=[];
        return;
    end
    vals=x(eligible);
    vals_sorted=sort(vals,'descend');
    kth_pos=min(k,numel(vals_sorted));
    cutoff=vals_sorted(kth_pos);
    tol=max(1e-12,1e-10*max(1,abs(cutoff)));
    idx=eligible(vals>=cutoff-tol);
end

function pct=jaccard_pct(a,b)
    a=unique(a(:)); b=unique(b(:));
    u=union(a,b);
    if isempty(u)
        pct=NaN;
    else
        pct=100*numel(intersect(a,b))/numel(u);
    end
end

function [estimate,se,lo,hi]=bootstrap_paired_difference(xa,xb,B,ci_level)
    xa=xa(:); xb=xb(:);
    valid=isfinite(xa) & isfinite(xb);
    d=xa(valid)-xb(valid);
    n=numel(d);
    if n==0
        estimate=NaN; se=NaN; lo=NaN; hi=NaN;
        return;
    end
    estimate=mean(d);
    boot=zeros(B,1);
    for b=1:B
        boot(b)=mean(d(randi(n,n,1)));
    end
    se=std(boot,0);
    alpha=(1-ci_level)/2;
    q=prctile(boot,[100*alpha,100*(1-alpha)]);
    lo=q(1); hi=q(2);
end

function idx=find_branch(mpc,fbus,tbus)
    idx=find((mpc.branch(:,1)==fbus & mpc.branch(:,2)==tbus) | ...
             (mpc.branch(:,1)==tbus & mpc.branch(:,2)==fbus),1);
    if isempty(idx)
        error('Branch %d-%d not found.',fbus,tbus);
    end
end
